# Generated by Django 5.2.6 on 2025-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='lift_score',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
