# Generated by Django 5.1.2 on 2025-06-15 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_alter_sub_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variants',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='adminside.product'),
        ),
    ]
