# Generated by Django 5.1.2 on 2025-06-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_brand_cart_category_color_material_order_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Female')], max_length=20),
        ),
    ]
