# Generated by Django 5.2.3 on 2025-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_alter_product_variants_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male')], max_length=20),
        ),
    ]
