# Generated by Django 5.2.3 on 2025-06-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_product_fit_type_alter_admin_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
