# Generated by Django 5.2.3 on 2025-06-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=50),
        ),
    ]
