# Generated by Django 5.2.3 on 2025-06-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0010_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
