# Generated by Django 5.2.3 on 2025-06-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_alter_product_name'),
        ('adminside', '0011_remove_product_sku'),
    ]

    operations = [
    ]
