# Generated by Django 5.2.3 on 2025-06-24 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0012_merge_0006_alter_product_name_0011_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminside.cart'),
        ),
        migrations.AlterField(
            model_name='order_details',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminside.order_master'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fit_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
