# Generated by Django 5.2.3 on 2025-06-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0021_product_ml_feature_vectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequently_bought_together',
            name='product_a_id',
        ),
        migrations.RemoveField(
            model_name='frequently_bought_together',
            name='product_b_id',
        ),
        migrations.RemoveField(
            model_name='ml_feature_vectors',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product_variant_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='product_tags',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_gallery',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_variants',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product_variants',
            name='size_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Cart_Items',
        ),
        migrations.DeleteModel(
            name='Frequently_Bought_Together',
        ),
        migrations.DeleteModel(
            name='ML_Feature_Vectors',
        ),
        migrations.DeleteModel(
            name='Order_Details',
        ),
        migrations.DeleteModel(
            name='Product_Tags',
        ),
        migrations.DeleteModel(
            name='Product_Gallery',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_Variants',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
