# Generated by Django 5.2.3 on 2025-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0023_product_ml_feature_vectors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='userside/user_profile_pictures/'),
        ),
    ]
