# Generated by Django 5.2.3 on 2025-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0024_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='country',
        ),
        migrations.AddField(
            model_name='user_address',
            name='address_name',
            field=models.CharField(default='Home', help_text='Name for this address (e.g., Home, Work)', max_length=80),
        ),
        migrations.AddField(
            model_name='user_address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order_master',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=25),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20),
        ),
    ]
