# Generated by Django 5.2.3 on 2025-07-19 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0025_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
