# Generated by Django 5.2.3 on 2025-07-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0025_remove_user_address_country_and_more'),
        ('adminside', '0026_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
    ]
