# Generated by Django 5.2.3 on 2025-07-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0027_merge_20250719_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recentlyviewed',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='recentlyviewed',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='recentlyviewed',
            unique_together={('user_id', 'product_id')},
        ),
    ]
