# Generated by Django 5.2.3 on 2025-07-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0028_rename_product_recentlyviewed_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_items',
            name='cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='adminside.cart'),
        ),
    ]
