# Generated by Django 5.2.3 on 2025-08-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0029_alter_cart_items_cart_id'),
        ('adminside', '0030_alter_user_gender'),
    ]

    operations = [
    ]
