# Generated by Django 5.2.3 on 2025-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0031_merge_20250806_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shipping_partners_id',
        ),
        migrations.AddField(
            model_name='order_master',
            name='mode_of_payment',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('upi', 'UPI Payment')], default='cod', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_status',
            field=models.CharField(choices=[('confirm', 'Confirm'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=30),
        ),
        migrations.DeleteModel(
            name='Shipping_Partners',
        ),
    ]
