# Generated by Django 5.2.3 on 2025-09-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0032_remove_shipping_shipping_partners_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
