# Generated by Django 5.2.3 on 2025-09-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0033_alter_payment_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='mode_of_payment',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Card Payment'), ('upi', 'UPI Payment')], default='cod', max_length=30),
        ),
    ]
