# Generated by Django 5.2.3 on 2025-09-10 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0034_alter_order_master_mode_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='sort_order',
        ),
    ]
