# Generated by Django 5.2.3 on 2025-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0035_remove_category_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_master',
            name='invoice_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('completed', 'Completed'), ('failed', 'Failed'), ('refund_initiated', 'Refund Initiated'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
