# Generated by Django 5.2.3 on 2025-09-17 18:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0036_order_master_invoice_uuid_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='invoice_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
