# Generated by Django 5.2.3 on 2025-09-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0037_alter_order_master_invoice_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_master',
            old_name='expected_delivery',
            new_name='excepted_delivery',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='excepted_delivery',
            new_name='expected_delivery',
        ),
    ]
