# Generated by Django 5.2.3 on 2025-09-25 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0038_rename_expected_delivery_order_master_excepted_delivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_master',
            old_name='excepted_delivery',
            new_name='expected_delivery',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='expected_delivery',
            new_name='excepted_delivery',
        ),
    ]
