# Generated by Django 5.2.3 on 2025-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0039_rename_excepted_delivery_order_master_expected_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_master',
            name='order_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
