# Generated by Django 5.2.3 on 2025-10-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0040_alter_order_master_expected_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='confidence_score',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='lift_score',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='support_score',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
