# Generated by Django 5.2.6 on 2025-09-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0041_reviewmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewMedia',
        ),
    ]
