# Generated by Django 5.2.3 on 2025-10-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0041_alter_frequently_bought_together_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='confidence_score',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='lift_score',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='frequently_bought_together',
            name='support_score',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
