# Generated by Django 5.2.3 on 2025-10-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0042_alter_frequently_bought_together_confidence_score_and_more'),
        ('adminside', '0042_delete_reviewmedia'),
    ]

    operations = [
    ]
