# Generated by Django 5.2.3 on 2025-10-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0043_merge_20251005_1456'),
        ('adminside', '0043_merge_20251005_2102'),
    ]

    operations = [
    ]
