# Generated by Django 5.2.3 on 2025-10-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0044_merge_20251005_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ml_feature_vectors',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminside.product'),
        ),
    ]
