"""
Django settings for vibedrobe project.

Generated by 'django-admin startproject' using Django 5.1.2.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# ===============================================================
# CORE SETTINGS (Non-sensitive)
# ===============================================================

DEBUG = True  # Default; overridden in local_settings.py if present
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'adminside',
    'userside',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vibedrobe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'adminside.context_processor.admin_profile_image',
                'adminside.context_processor.custom_alerts',
                'userside.context_processor.custom_message_tags',
                'userside.context_processor.cart_and_wishlist_count',
                'userside.context_processor.cart_drawer',
            ],
        },
    },
]

WSGI_APPLICATION = 'vibedrobe.wsgi.application'

# ===============================================================
# DEFAULT DATABASE PLACEHOLDER (Overridden in local_settings.py)
# ===============================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / "db.sqlite3",
    }
}

# ===============================================================
# AUTH & PASSWORDS
# ===============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

AUTH_USER_MODEL = 'adminside.User'

# ===============================================================
# INTERNATIONALIZATION
# ===============================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# ===============================================================
# STATIC & MEDIA FILES
# ===============================================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===============================================================
# EMAIL & PAYMENT (Placeholders)
# These are overridden by local_settings.py
# ===============================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = 'VibeDrobe <noreply@vibedrobe.com>'
CONTACT_EMAIL = ''

RAZORPAY_KEY_ID = ''
RAZORPAY_KEY_SECRET = ''

# ===============================================================
# IMPORT LOCAL SETTINGS (For sensitive data)
# ===============================================================
try:
    from .local_settings import *
except ImportError:
    print("⚠️  Warning: local_settings.py not found. Using default/empty values.")
